package net.xdexamples.jse.examples.javax.xml.soap;

import net.xdexamples.BaseExample;

import javax.xml.soap.SOAPConstants;

public class SOAPConstantsExample extends BaseExample<SOAPConstants> {
    @Override
    protected void scaffold(SOAPConstants instance) throws Throwable {
/*
DEFAULT_SOAP_PROTOCOL
DYNAMIC_SOAP_PROTOCOL
SOAP_1_1_CONTENT_TYPE
SOAP_1_1_PROTOCOL
SOAP_1_2_CONTENT_TYPE
SOAP_1_2_PROTOCOL
SOAP_DATAENCODINGUNKNOWN_FAULT
SOAP_ENV_PREFIX
SOAP_MUSTUNDERSTAND_FAULT
SOAP_RECEIVER_FAULT
SOAP_SENDER_FAULT
SOAP_VERSIONMISMATCH_FAULT
URI_NS_SOAP_1_1_ENVELOPE
URI_NS_SOAP_1_2_ENCODING
URI_NS_SOAP_1_2_ENVELOPE
URI_NS_SOAP_ENCODING
URI_NS_SOAP_ENVELOPE
URI_SOAP_1_2_ROLE_NEXT
URI_SOAP_1_2_ROLE_NONE
URI_SOAP_1_2_ROLE_ULTIMATE_RECEIVER
URI_SOAP_ACTOR_NEXT
 */
    }
}
