package trove.pages;

import trove.Languages;
import trove.Page;
import trove.RenderContext;

import java.io.IOException;
import java.util.List;

public class PowerShellNetModules extends Page {

    public PowerShellNetModules() {
        super(
                makeLocation(PowerShell.LOCATION, "netModules"),
                "Network Modules",
                List.of(Languages.PowerShell)
        );
    }

    @Override
    protected void render(RenderContext renderContext) throws IOException {
        p("List of PowerShell Network Modules");
        ul(linesCode("""
                NetAdapter
                NetConnection
                NetEventPacketCapture
                NetLbfo
                NetNat
                NetQos
                NetSecurity
                NetSwitchTeam
                NetTCPIP
                NetworkConnectivityStatus
                NetworkSwitchManager
                NetworkTransition"""));
        section(markdown("`NetAdapter`"));
        ul(linesCode("""
                Disable-NetAdapter
                Disable-NetAdapterBinding
                Disable-NetAdapterChecksumOffload
                Disable-NetAdapterEncapsulatedPacketTaskOffload
                Disable-NetAdapterIPsecOffload
                Disable-NetAdapterLso
                Disable-NetAdapterPacketDirect
                Disable-NetAdapterPowerManagement
                Disable-NetAdapterQos
                Disable-NetAdapterRdma
                Disable-NetAdapterRsc
                Disable-NetAdapterRss
                Disable-NetAdapterSriov
                Disable-NetAdapterUso
                Disable-NetAdapterVmq
                Enable-NetAdapter
                Enable-NetAdapterBinding
                Enable-NetAdapterChecksumOffload
                Enable-NetAdapterEncapsulatedPacketTaskOffload
                Enable-NetAdapterIPsecOffload
                Enable-NetAdapterLso
                Enable-NetAdapterPacketDirect
                Enable-NetAdapterPowerManagement
                Enable-NetAdapterQos
                Enable-NetAdapterRdma
                Enable-NetAdapterRsc
                Enable-NetAdapterRss
                Enable-NetAdapterSriov
                Enable-NetAdapterUso
                Enable-NetAdapterVmq
                Get-NetAdapter
                Get-NetAdapterAdvancedProperty
                Get-NetAdapterBinding
                Get-NetAdapterChecksumOffload
                Get-NetAdapterEncapsulatedPacketTaskOffload
                Get-NetAdapterHardwareInfo
                Get-NetAdapterIPsecOffload
                Get-NetAdapterLso
                Get-NetAdapterPacketDirect
                Get-NetAdapterPowerManagement
                Get-NetAdapterQos
                Get-NetAdapterRdma
                Get-NetAdapterRsc
                Get-NetAdapterRss
                Get-NetAdapterSriov
                Get-NetAdapterSriovVf
                Get-NetAdapterStatistics
                Get-NetAdapterUso
                Get-NetAdapterVmq
                Get-NetAdapterVmqQueue
                Get-NetAdapterVPort
                New-NetAdapterAdvancedProperty
                Remove-NetAdapterAdvancedProperty
                Rename-NetAdapter
                Reset-NetAdapterAdvancedProperty
                Restart-NetAdapter
                Set-NetAdapter
                Set-NetAdapterAdvancedProperty
                Set-NetAdapterBinding
                Set-NetAdapterChecksumOffload
                Set-NetAdapterEncapsulatedPacketTaskOffload
                Set-NetAdapterIPsecOffload
                Set-NetAdapterLso
                Set-NetAdapterPacketDirect
                Set-NetAdapterPowerManagement
                Set-NetAdapterQos
                Set-NetAdapterRdma
                Set-NetAdapterRsc
                Set-NetAdapterRss
                Set-NetAdapterSriov
                Set-NetAdapterUso
                Set-NetAdapterVmq"""));
        section(markdown("`NetConnection`"));
        ul(linesCode("""
                Get-NetConnectionProfile
                Set-NetConnectionProfile"""));
        section(markdown("`NetEventPacketCapture`"));
        ul(linesCode("""
                Add-NetEventNetworkAdapter
                Add-NetEventPacketCaptureProvider
                Add-NetEventProvider
                Add-NetEventVFPProvider
                Add-NetEventVmNetworkAdapter
                Add-NetEventVmSwitch
                Add-NetEventVmSwitchProvider
                Add-NetEventWFPCaptureProvider
                Get-NetEventNetworkAdapter
                Get-NetEventPacketCaptureProvider
                Get-NetEventProvider
                Get-NetEventSession
                Get-NetEventVFPProvider
                Get-NetEventVmNetworkAdapter
                Get-NetEventVmSwitch
                Get-NetEventVmSwitchProvider
                Get-NetEventWFPCaptureProvider
                New-NetEventSession
                Remove-NetEventNetworkAdapter
                Remove-NetEventPacketCaptureProvider
                Remove-NetEventProvider
                Remove-NetEventSession
                Remove-NetEventVFPProvider
                Remove-NetEventVmNetworkAdapter
                Remove-NetEventVmSwitch
                Remove-NetEventVmSwitchProvider
                Remove-NetEventWFPCaptureProvider
                Set-NetEventPacketCaptureProvider
                Set-NetEventProvider
                Set-NetEventSession
                Set-NetEventVFPProvider
                Set-NetEventVmSwitchProvider
                Set-NetEventWFPCaptureProvider
                Start-NetEventSession
                Stop-NetEventSession"""));
        section(markdown("`NetLbfo`"));
        ul(linesCode("""
                Add-NetLbfoTeamMember
                Add-NetLbfoTeamNic
                Get-NetLbfoTeam
                Get-NetLbfoTeamMember
                Get-NetLbfoTeamNic
                New-NetLbfoTeam
                Remove-NetLbfoTeam
                Remove-NetLbfoTeamMember
                Remove-NetLbfoTeamNic
                Rename-NetLbfoTeam
                Set-NetLbfoTeam
                Set-NetLbfoTeamMember
                Set-NetLbfoTeamNic"""));
        section(markdown("`NetNat`"));
        ul(linesCode("""
                Add-NetNatExternalAddress
                Add-NetNatStaticMapping
                Get-NetNat
                Get-NetNatExternalAddress
                Get-NetNatGlobal
                Get-NetNatSession
                Get-NetNatStaticMapping
                New-NetNat
                Remove-NetNat
                Remove-NetNatExternalAddress
                Remove-NetNatStaticMapping
                Set-NetNat
                Set-NetNatGlobal"""));
        section(markdown("`NetQos`"));
        ul(linesCode("""
                Get-NetQosPolicy
                New-NetQosPolicy
                Remove-NetQosPolicy
                Set-NetQosPolicy"""));
        section(markdown("`NetSecurity`"));
        ul(linesCode("""
                Copy-NetFirewallRule
                Copy-NetIPsecMainModeCryptoSet
                Copy-NetIPsecMainModeRule
                Copy-NetIPsecPhase1AuthSet
                Copy-NetIPsecPhase2AuthSet
                Copy-NetIPsecQuickModeCryptoSet
                Copy-NetIPsecRule
                Disable-NetFirewallRule
                Disable-NetIPsecMainModeRule
                Disable-NetIPsecRule
                Enable-NetFirewallRule
                Enable-NetIPsecMainModeRule
                Enable-NetIPsecRule
                Find-NetIPsecRule
                Get-DAPolicyChange
                Get-NetFirewallAddressFilter
                Get-NetFirewallApplicationFilter
                Get-NetFirewallDynamicKeywordAddress
                Get-NetFirewallInterfaceFilter
                Get-NetFirewallInterfaceTypeFilter
                Get-NetFirewallPortFilter
                Get-NetFirewallProfile
                Get-NetFirewallRule
                Get-NetFirewallSecurityFilter
                Get-NetFirewallServiceFilter
                Get-NetFirewallSetting
                Get-NetIPsecDospSetting
                Get-NetIPsecMainModeCryptoSet
                Get-NetIPsecMainModeRule
                Get-NetIPsecMainModeSA
                Get-NetIPsecPhase1AuthSet
                Get-NetIPsecPhase2AuthSet
                Get-NetIPsecQuickModeCryptoSet
                Get-NetIPsecQuickModeSA
                Get-NetIPsecRule
                New-NetFirewallDynamicKeywordAddress
                New-NetFirewallRule
                New-NetIPsecAuthProposal
                New-NetIPsecDospSetting
                New-NetIPsecMainModeCryptoProposal
                New-NetIPsecMainModeCryptoSet
                New-NetIPsecMainModeRule
                New-NetIPsecPhase1AuthSet
                New-NetIPsecPhase2AuthSet
                New-NetIPsecQuickModeCryptoProposal
                New-NetIPsecQuickModeCryptoSet
                New-NetIPsecRule
                Open-NetGPO
                Remove-NetFirewallDynamicKeywordAddress
                Remove-NetFirewallRule
                Remove-NetIPsecDospSetting
                Remove-NetIPsecMainModeCryptoSet
                Remove-NetIPsecMainModeRule
                Remove-NetIPsecMainModeSA
                Remove-NetIPsecPhase1AuthSet
                Remove-NetIPsecPhase2AuthSet
                Remove-NetIPsecQuickModeCryptoSet
                Remove-NetIPsecQuickModeSA
                Remove-NetIPsecRule
                Rename-NetFirewallRule
                Rename-NetIPsecMainModeCryptoSet
                Rename-NetIPsecMainModeRule
                Rename-NetIPsecPhase1AuthSet
                Rename-NetIPsecPhase2AuthSet
                Rename-NetIPsecQuickModeCryptoSet
                Rename-NetIPsecRule
                Save-NetGPO
                Set-NetFirewallAddressFilter
                Set-NetFirewallApplicationFilter
                Set-NetFirewallInterfaceFilter
                Set-NetFirewallInterfaceTypeFilter
                Set-NetFirewallPortFilter
                Set-NetFirewallProfile
                Set-NetFirewallRule
                Set-NetFirewallSecurityFilter
                Set-NetFirewallServiceFilter
                Set-NetFirewallSetting
                Set-NetIPsecDospSetting
                Set-NetIPsecMainModeCryptoSet
                Set-NetIPsecMainModeRule
                Set-NetIPsecPhase1AuthSet
                Set-NetIPsecPhase2AuthSet
                Set-NetIPsecQuickModeCryptoSet
                Set-NetIPsecRule
                Show-NetFirewallRule
                Show-NetIPsecRule
                Sync-NetIPsecRule
                Update-NetFirewallDynamicKeywordAddress
                Update-NetIPsecRule"""));
        section(markdown("`NetSwitchTeam`"));
        ul(linesCode("""
                Add-NetSwitchTeamMember
                Get-NetSwitchTeam
                Get-NetSwitchTeamMember
                New-NetSwitchTeam
                Remove-NetSwitchTeam
                Remove-NetSwitchTeamMember
                Rename-NetSwitchTeam"""));
        section(markdown("`NetTCPIP`"));
        ul(linesCode("""
                Find-NetRoute
                Get-NetCompartment
                Get-NetIPAddress
                Get-NetIPConfiguration
                Get-NetIPInterface
                Get-NetIPv4Protocol
                Get-NetIPv6Protocol
                Get-NetNeighbor
                Get-NetOffloadGlobalSetting
                Get-NetPrefixPolicy
                Get-NetRoute
                Get-NetTCPConnection
                Get-NetTCPSetting
                Get-NetTransportFilter
                Get-NetUDPEndpoint
                Get-NetUDPSetting
                New-NetIPAddress
                New-NetNeighbor
                New-NetRoute
                New-NetTransportFilter
                Remove-NetIPAddress
                Remove-NetNeighbor
                Remove-NetRoute
                Remove-NetTransportFilter
                Set-NetIPAddress
                Set-NetIPInterface
                Set-NetIPv4Protocol
                Set-NetIPv6Protocol
                Set-NetNeighbor
                Set-NetOffloadGlobalSetting
                Set-NetRoute
                Set-NetTCPSetting
                Set-NetUDPSetting
                Test-NetConnection"""));
        section(markdown("`NetworkConnectivityStatus`"));
        ul(linesCode("""
                Get-DAConnectionStatus
                Get-NCSIPolicyConfiguration
                Reset-NCSIPolicyConfiguration
                Set-NCSIPolicyConfiguration"""));
        section(markdown("`NetworkSwitchManager`"));
        ul(linesCode("""
                Disable-NetworkSwitchEthernetPort
                Disable-NetworkSwitchFeature
                Disable-NetworkSwitchVlan
                Enable-NetworkSwitchEthernetPort
                Enable-NetworkSwitchFeature
                Enable-NetworkSwitchVlan
                Get-NetworkSwitchEthernetPort
                Get-NetworkSwitchFeature
                Get-NetworkSwitchGlobalData
                Get-NetworkSwitchVlan
                New-NetworkSwitchVlan
                Remove-NetworkSwitchEthernetPortIPAddress
                Remove-NetworkSwitchVlan
                Restore-NetworkSwitchConfiguration
                Save-NetworkSwitchConfiguration
                Set-NetworkSwitchEthernetPortIPAddress
                Set-NetworkSwitchPortMode
                Set-NetworkSwitchPortProperty
                Set-NetworkSwitchVlanProperty"""));
        section(markdown("`NetworkTransition`"));
        ul(linesCode("""
                Add-NetIPHttpsCertBinding
                Disable-NetDnsTransitionConfiguration
                Disable-NetIPHttpsProfile
                Disable-NetNatTransitionConfiguration
                Enable-NetDnsTransitionConfiguration
                Enable-NetIPHttpsProfile
                Enable-NetNatTransitionConfiguration
                Get-Net6to4Configuration
                Get-NetDnsTransitionConfiguration
                Get-NetDnsTransitionMonitoring
                Get-NetIPHttpsConfiguration
                Get-NetIPHttpsState
                Get-NetIsatapConfiguration
                Get-NetNatTransitionConfiguration
                Get-NetNatTransitionMonitoring
                Get-NetTeredoConfiguration
                Get-NetTeredoState
                New-NetIPHttpsConfiguration
                New-NetNatTransitionConfiguration
                Remove-NetIPHttpsCertBinding
                Remove-NetIPHttpsConfiguration
                Remove-NetNatTransitionConfiguration
                Rename-NetIPHttpsConfiguration
                Reset-Net6to4Configuration
                Reset-NetDnsTransitionConfiguration
                Reset-NetIPHttpsConfiguration
                Reset-NetIsatapConfiguration
                Reset-NetTeredoConfiguration
                Set-Net6to4Configuration
                Set-NetDnsTransitionConfiguration
                Set-NetIPHttpsConfiguration
                Set-NetIsatapConfiguration
                Set-NetNatTransitionConfiguration
                Set-NetTeredoConfiguration"""));
    }
}
