package net.xdexamples.jse.examples.java.security.cert;

import net.xdexamples.BaseExample;

import java.security.cert.X509CertSelector;

public class X509CertSelectorExample extends BaseExample<X509CertSelector> {
    @Override
    protected void scaffold(X509CertSelector instance) throws Throwable {
/*
X509CertSelector
addPathToName
addPathToName
addSubjectAlternativeName
addSubjectAlternativeName
clone
getAuthorityKeyIdentifier
getBasicConstraints
getCertificate
getCertificateValid
getExtendedKeyUsage
getIssuer
getIssuerAsBytes
getIssuerAsString
getKeyUsage
getMatchAllSubjectAltNames
getNameConstraints
getPathToNames
getPolicy
getPrivateKeyValid
getSerialNumber
getSubject
getSubjectAlternativeNames
getSubjectAsBytes
getSubjectAsString
getSubjectKeyIdentifier
getSubjectPublicKey
getSubjectPublicKeyAlgID
match
setAuthorityKeyIdentifier
setBasicConstraints
setCertificate
setCertificateValid
setExtendedKeyUsage
setIssuer
setIssuer
setIssuer
setKeyUsage
setMatchAllSubjectAltNames
setNameConstraints
setPathToNames
setPolicy
setPrivateKeyValid
setSerialNumber
setSubject
setSubject
setSubject
setSubjectAlternativeNames
setSubjectKeyIdentifier
setSubjectPublicKey
setSubjectPublicKey
setSubjectPublicKeyAlgID
toString
 */
    }
}
