package net.xdexamples.jse.index.java.net;

import net.xdexamples.BaseExample;

import java.net.URLConnection;

public class URLConnectionExample extends BaseExample<URLConnection> {
    @Override
    protected void scaffold(URLConnection instance) throws Throwable {
/*
addRequestProperty
connect
getAllowUserInteraction
getConnectTimeout
getContent
getContent
getContentEncoding
getContentLength
getContentLengthLong
getContentType
getDate
getDefaultAllowUserInteraction
getDefaultRequestProperty
getDefaultUseCaches
getDefaultUseCaches
getDoInput
getDoOutput
getExpiration
getFileNameMap
getHeaderField
getHeaderField
getHeaderFieldDate
getHeaderFieldInt
getHeaderFieldKey
getHeaderFieldLong
getHeaderFields
getIfModifiedSince
getInputStream
getLastModified
getOutputStream
getPermission
getReadTimeout
getRequestProperties
getRequestProperty
getURL
getUseCaches
guessContentTypeFromName
guessContentTypeFromStream
setAllowUserInteraction
setConnectTimeout
setContentHandlerFactory
setDefaultAllowUserInteraction
setDefaultRequestProperty
setDefaultUseCaches
setDefaultUseCaches
setDoInput
setDoOutput
setFileNameMap
setIfModifiedSince
setReadTimeout
setRequestProperty
setUseCaches
toString
 */
    }
}
